### ISSUE TITLE
Variables can not be interpolated into name fields.

### ISSUE THREAD

**Issue by 11xor6** [walmartlabs/concord#187]
For example:
```yaml
- name: Validating client ${item.name}
  call: validate-client
  in:
    staticClient: ${item}
  withItems: ${clients}
```
Outputs `Validating client ${item.name}` instead of something like `Validating client Foo`

Additionally this seems to be inconsistent, as (at lease some) tasks seem to do this properly.
