### ISSUE TITLE
Conditions in generic triggers

### ISSUE THREAD

**Issue by ibodrov** [walmartlabs/concord#268]
We need to document the security requirements for calling trigger endpoints.
The issue below is invalid, it is the expected behaviour of `runtime: concord-v1`. The *original* problem was causes by the lack of permissions for the project.

Original description:

Assuming the default server configuration and a concord.yml like so

```yaml
triggers:
  - my_trigger:
      entryPoint: default
      conditions:
        a_field: a_value

flows:
  default:
    - log: "Hello!"
```

It produces the following trigger:
![image](https://user-images.githubusercontent.com/826959/101522795-bcf35880-3955-11eb-8a3d-150982cdcc20.png)

Note the nested `conditions`.

To activate this trigger, I would need to include the `conditions` field in the payload too:
```json
{
    "conditions": {
        "a_field": "a_value"
    }
}
```

Which is different from the logic of other trigger types, the `conditions` field's content should be used for matching and not the top-level fields in the trigger.
