### ISSUE TITLE
Implement masking secrets in the runner logs

### ISSUE THREAD

**Issue by nbarabash** [walmartlabs/concord#361]
Form inputs marked with "inputType: "password" are insecurely printed in the runner logs.

forms:
    - vaultLdapPass: { label: "Vault Ldap Password:",  type: "string?", inputType: "password", placeholder: "optional, type only if you want to change Vault Ldap Password"  }

configuration:
  runner:
    logLevel: "WARN"
    events:
      recordTaskInVars: false
      inVarsBlacklist:
        - "vaultLdapPass"
 
flows:
  vaultSecretReset:
    - form: vaultSecretReset
      yield: true
    - call: runDocker
      in:
        dockerCmd: |
          echo token=${vaultSecretReset.vaultLdapPass} >>  mysecretfile

**log output contains:**

23:34:13 [WARN ] call ['docker......
echo token=_testtoken_ >>  mysecretfile

where _vaultLdapPass_ was set value "_testtoken_" in the secured form input.

**Comment by benbroadaway** [comment]
For the specific issue here, this is exactly why you should use [environment variables](https://concord.walmart.com/docs/plugins/docker.html#environment-variables) for the docker task, rather than direct string interpolation in the command.

```yaml
- task: docker
  in:
    image: "library/alpine"
    cmd: "echo token=$VAULT_LDAP_PASS >> mysecretfile"
    env:
      VAULT_LDAP_PASS: "${vaultSecretReset.vaultLdapPass}"
```
