### ISSUE TITLE
Possible stale workDir references after resuming a process

### ISSUE THREAD

**Issue by ibodrov** [walmartlabs/concord#373]
The `workDir` value changes between executions (including resuming of suspended processes).
If a process saves the current `${workDir}` value in a variable, it might end up with a "stale" value.

E.g.
```yaml
imports:
  - git:
      url: "https://github.com/walmartlabs/concord.git"
      version: "master"
      path: "examples/hello_world"
      dest: "my_stuff"

configuration:
  arguments:
    pathToAFile: "${workDir}/my_stuff/concord.yml"
      
flows:
 default:
   - expr: ${resource.asYaml(pathToAFile)}
   
   - form: myForm
     yield: true
     fields:
       - x: { type: string }
   
   - expr: ${resource.asYaml(pathToAFile)}
```

Steps to reproduce locally:
- start the `concord.yml` from the example above;
- wait for the process to suspend;
- submit the form.

Expected result:
- the process can read `pathToAFile`

Actual result:
```
19:08:59 [WARN ] eval ['${resource.asYaml(pathToAFile)}'] -> error: java.nio.file.NoSuchFileException: /tmp/prefork8429794436487714772/payload/my_stuff/concord.yml
19:08:59 [ERROR] main -> unhandled exception
java.nio.file.NoSuchFileException: /tmp/prefork8429794436487714772/payload/my_stuff/concord.yml
```

Affects both v1 and v2 runtimes.
