### ISSUE TITLE
concord-task: broken runtime-v2 methods/actions

### ISSUE THREAD

**Issue by benbroadaway** [walmartlabs/concord#486]
## `suspendForCompletion()`

https://github.com/walmartlabs/concord/blob/228b21256f5156bb0eb2e76a3143ce2318c198b2/plugins/tasks/concord/src/main/java/com/walmartlabs/concord/client/v2/ConcordTaskV2.java#L83-L87

The task is not actually suspending the process. It just continues on.

## ~process info not returned when using `sync: true`~

~In the runtime-v1 implementation, the final process status info is returned/set--not just the process IDs. We need to return similar data, or update the docs to indicate that's not how it works and `concord.waitForCompletion(...)` needs to be called afterwards (though that makes less sense).~

## returning UUIDs for process IDs only accepting Strings

The `start` and `fork` actions return process IDs as `UUID` objects. Other methods for checking the status like `waitForCompletion` expect the given IDs to be Strings. So you cannot currently do a couple simple calls like

```yaml
- task: concord
  in:
    sync: false
    # ...
  out: result  # only contains ids
- expr: ${concord.waitForCompletion(result.ids)}
  out: processResults

# results in
# [ERROR] (concord.yml): Error @ line: 183, col: 7. java.util.UUID cannot be cast to java.lang.String
```

Instead, you have to do an extra step of `toString()`-ing the UUIDs

```yaml
- task: concord
  in:
    sync: true
    suspend: true
    ...
  out: result  # only contains ids
# converts UUID ids to String first
- expr: ${concord.waitForCompletion(result.ids.stream().map(id -> id.toString()).toList())}
  out: processResults
```

The plugin should be more careful with the 

## `id` vs `ids` when forks count is 1 vs more than 1

The returned data when using the `fork` action varies depending on the number of forks.

```yaml
- task: concord
  in:
    action: fork
    forks:
    - entryPoint: flowA
  out: result  # just one fork gives result.id

- task: concord
  in:
    action: fork
    forks:
    - entryPoint: flowA
    - entryPoint: flowB
  out: result  # multiple forks gives result.ids
```

This should be more consistent. I think it should always return `ids` when forking.
