### ISSUE TITLE
Got an error "ELResolver cannot handle a null base Object with identifier" when developing task plugin

### ISSUE THREAD

**Issue by everimbaq** [walmartlabs/concord#6]
step1. I implemented Task interface and created my plugin "zajenkins" in package "com.za.tech.concord.plugins.jenkins".
```java
@Named("zajenkins")
public class ZaJenkinsTask implements Task {...}
```
step2. I created a flow calling the task and run it.
```yaml
configuration:
  dependencies:
#  - mvn://com.walmartlabs.concord.plugins:jenkins-task:1.11.0
  - http://10.139.32.180:8080/nexus/content/repositories/snapshots/com/za/tech/concord/plugin/jenkins/1.0-SNAPSHOT/jenkins-1.0-20190710.033237-4-sources.jar
  entryPoint: "default"
flows:
  default:
  - task: zajenkins
    in:
      baseUrl: "http://172.28.155.241:8081"
      username: "za-zhaogang"
......
```
step3. I got an error "ELResolver cannot handle a null base Object with identifier 'zajenkins".
![image](https://user-images.githubusercontent.com/7394813/60938580-08d84300-a307-11e9-9a00-583b90053475.png)
