### ISSUE TITLE
runtime-v2: incorrect events configuration merging with profiles

### ISSUE THREAD

**Issue by benbroadaway** [walmartlabs/concord#629]
Event recording configuration gets wiped out if an active profile is set.

For example:
```yaml
configuration:
  events:
    recordTaskInVars: true

profiles:
  myProfile:
    arguments:
      myString: hello
```
If `myProfile` is active, the `events` setting is not respected. Interestingly, the merged config (e.g. `_main.json` in process state) _does_ contain the expected events configuration
