### ISSUE TITLE
out variables for empty loop

### ISSUE THREAD

**Issue by brig** [walmartlabs/concord#748]
simple example:
```
flows:
  default:
    - call: test
      out: myVar
      loop:
        items: []

    - log: ${myVar}

  test:
    - log: "in test"
    - set:
        myVar: "${item}"
```

```
14:13:04.171 [main] (concord.yml): Error @ line: 8, col: 7. Can't find the specified variable in '${myVar}'. Check if it is defined in the current scope. Details: ELResolver cannot handle a null base Object with identifier 'myVar'
```

little bit unexpected for me, what do you think?
