### ISSUE TITLE
How to init different configs while processing different flows?

### ISSUE THREAD

**Issue by everimbaq** [walmartlabs/concord#9]
I have two flows and its configurations defined in the concord directory like below. 
concord.yml
```yaml
flows:
  flow1:
  - log: "thisIsFlow1 ${arg1}"
 flow2:
  - log: "thisIsFlow2 ${arg2}"
```
concord/flow1.yml
```yaml
configuration:
  arguments:
    arg1: ${arg1}
```

concord/flow2.yml
```yaml
configuration:
  arguments:
    arg2: ${arg2}
```

Now when i call /api/v1/process  flow1 with arg1, i'll get an error "ELResolver cannot handle a null base Object with identifier 'arg2'" warning me to put parameter arg2 in request.

I want to just init arg1 when i call flow1, just init arg2 when i call flow2. The resources and profiles features seems to be a share of configs, it didn't solve my problem.  How could i do that?

**Comment by ibodrov** [comment]
That what profiles are for: https://concord.walmartlabs.com/docs/getting-started/concord-dsl.html#named-profiles-in-profiles

All Concord files in a repo are loaded and merged together, check out the load rules for the `concord` folder here:
https://concord.walmartlabs.com/docs/getting-started/concord-dsl.html#concord-folder

Also,
```yaml
configuration:
  arguments:
    arg1: ${arg1}
```
doesn't make much sense. You don't have to declare process arguments. E.g.
```yaml
flows:
  flow1:
    - log: "Hello, ${arg1}"
```
```
$ curl -ikn -F arguments.arg1=Concord -F entryPoint=flow1 ...
```
should work just fine.
